### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by alihanaktay** [mobillium/MobilliumBuilders#22]
Hello,

I have some feature requests if it is possible can we add that.

Add background color to stackviews
Add isUserInteractionEnable flag to UIElements
Add isHidden flag to UIElements
Add setAccessibilityIdentifier and isAccessibilityElement flags to UIElements for UITests

Thank you!

**Comment by mrtcelebi** [comment]
Those features you have requested added on 1.1.0 release version and published.
[https://github.com/mobillium/MobilliumBuilders/releases](url)
